CONFIG_ZMK_KEYBOARD_NAME="Macropad"

CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y

CONFIG_I2C=y
CONFIG_SSD1306=y
CONFIG_SERIAL=n
CONFIG_SPI=n

CONFIG_ZMK_KSCAN_MATRIX_POLLING=y

CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

## Battery/power settings
# IDLE: still on but 'low power' -- ms (15 seconds)
CONFIG_ZMK_IDLE_TIMEOUT=15000
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y

# SLEEP: completely off -- ms (15 minutes)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

## OLED display settings
CONFIG_ZMK_DISPLAY=y

# HID indicators
CONFIG_ZMK_HID_INDICATORS=y

# Layer status widget
CONFIG_ZMK_WIDGET_LAYER_STATUS=y

# Battery status widget
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y

# Output status widget
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
